resolver: lts-7.8

# User packages to be built.
# Various formats can be used as shown in the example below.
#
packages:
- .
- location:
    git: https://github.com/reflex-frp/reflex
    commit: 91299fce0bb2caddfba35af6608df57dd31e3690
    # Latest develop comment at the time of writing
  extra-dep: true
- location:
    git: https://github.com/hamishmack/reflex-dom
    commit: 00c773be07693f38d981d6b99fac4a0571d45bd0
  extra-dep: true
- location:
    git: https://github.com/ghcjs/jsaddle
    commit: 02f215aec0622300fd68f0200c813356ed7cd738
  subdirs:
  - jsaddle
  - jsaddle-warp
  extra-dep: true
- location:
    git: https://github.com/ghcjs/jsaddle-dom
    commit: 06351fe3562a2e6d096f6c862a9f5694ffd800d8
  extra-dep: true

extra-deps:
- ghcjs-dom-0.7.0.3
- ghcjs-dom-jsaddle-0.7.0.3
- jsaddle-warp-0.7.0.0
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- zenc-0.1.1
- MemoTrie-0.6.7
- newtype-generics-0.5
- wai-websockets-3.0.1.1

flags:
  wai-websockets:
    example: false

extra-package-dbs: []
